-- CreateEnum
CREATE TYPE "APPROVAL_STATUS" AS ENUM ('ALLOWED', 'REJECTED', 'WAITING');

-- CreateEnum
CREATE TYPE "LOAN_STATUS" AS ENUM ('FINISH', 'USED', 'NOT_STARTED');

-- AlterTable
ALTER TABLE "Rent" ADD COLUMN     "loanStatus" "LOAN_STATUS" DEFAULT 'NOT_STARTED',
ADD COLUMN     "rentApprovalStatus" "APPROVAL_STATUS" DEFAULT 'WAITING';
